# Google Cloud Platform Deployment Configuration
# Cloud Run deployment for Backend

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bluepeak-backend
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '1'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/PROJECT_ID/bluepeak-backend:latest
          ports:
            - name: http1
              containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: DEBUG
              value: "False"
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bluepeak-secrets
                  key: anthropic-api-key
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bluepeak-secrets
                  key: supabase-url
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: bluepeak-secrets
                  key: supabase-key
            - name: REDIS_HOST
              value: "REDIS_IP"
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

---
# Cloud Run deployment for Frontend

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bluepeak-frontend
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '5'
        autoscaling.knative.dev/minScale: '1'
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/bluepeak-frontend:latest
          ports:
            - name: http1
              containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "https://bluepeak-backend-HASH.run.app/api/v1"
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '500m'
              memory: 256Mi
